# Generated by Django 3.1.6 on 2021-02-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='blogUser',
        ),
    ]
