# Generated by Django 3.1.6 on 2021-02-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210218_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloguser',
            options={'verbose_name_plural': 'User'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
