# Generated by Django 3.1.6 on 2021-02-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210218_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='lastUpdated',
            field=models.DateTimeField(blank=True),
        ),
    ]
