# Generated by Django 3.1.6 on 2021-02-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210218_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='lastUpdated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
